OttistTech/ms-indespensa

src/main/java/com/ottistech/indespensa/api/ms_indespensa/model/Address.java
src/main/java/com/ottistech/indespensa/api/ms_indespensa/model/Campaign.java
src/main/java/com/ottistech/indespensa/api/ms_indespensa/model/Category.java
src/main/java/com/ottistech/indespensa/api/ms_indespensa/model/CompletedRecipe.java
src/main/java/com/ottistech/indespensa/api/ms_indespensa/model/EnterpriseProduct.java
src/main/java/com/ottistech/indespensa/api/ms_indespensa/model/Food.java
src/main/java/com/ottistech/indespensa/api/ms_indespensa/model/ListItem.java
src/main/java/com/ottistech/indespensa/api/ms_indespensa/model/Order.java
src/main/java/com/ottistech/indespensa/api/ms_indespensa/model/OrderItem.java
src/main/java/com/ottistech/indespensa/api/ms_indespensa/model/PantryItem.java
src/main/java/com/ottistech/indespensa/api/ms_indespensa/model/Product.java
src/main/java/com/ottistech/indespensa/api/ms_indespensa/model/Recipe.java
src/main/java/com/ottistech/indespensa/api/ms_indespensa/model/RecipeIngredient.java
src/main/java/com/ottistech/indespensa/api/ms_indespensa/model/User.java

[Tarefa relacionada](https://trello.com/c/7m73l3RJ/82-criar-as-entidades-da-api-v1)
Criar a primeira versão das entidades da API, com o banco sendo normalizado pela Equipe de Dados.
Criação de classes que representam tabelas do banco de dados.
|❌| …

Criação das entidades da API

---

src/main/java/com/ottistech/indespensa/api/ms_indespensa/controller/UserController.java
src/main/java/com/ottistech/indespensa/api/ms_indespensa/dto/LoginUserDTO.java
src/main/java/com/ottistech/indespensa/api/ms_indespensa/dto/UserCredentialsResponse.java
src/main/java/com/ottistech/indespensa/api/ms_indespensa/exception/GlobalExceptionHandler.java
src/main/java/com/ottistech/indespensa/api/ms_indespensa/exception/IncorrectPasswordException.java
src/main/java/com/ottistech/indespensa/api/ms_indespensa/exception/UserNotFoundException.java
src/main/java/com/ottistech/indespensa/api/ms_indespensa/service/UserService.java

[Tarefa relacionada](https://trello.com/c/tVEklyFG/84-criar-endpoints-de-login)
.
Permitir que o usuário faça login e obtenha suas credenciais para uso do app
.
Criação do endpoint de login com as seguintes funcionalidades:
- Recebimento de email e senha
- Verificação da existência do usuário (caso contrário, lança exceção)
- Verificação da senha (caso contrário, lança exceção)
- Em caso de sucesso, retorna as credenciais necessárias para o usuário utilizar o app
|✅| Minhas …

Criação do endpoint de login

---

src/main/java/com/ottistech/indespensa/api/ms_indespensa/controller/UserController.java
src/main/java/com/ottistech/indespensa/api/ms_indespensa/exception/GlobalExceptionHandler.java
src/main/java/com/ottistech/indespensa/api/ms_indespensa/exception/UserAlreadyDeactivatedException.java
src/main/java/com/ottistech/indespensa/api/ms_indespensa/service/UserService.java

[Tarefa relacionada](https://trello.com/c/qbm2EsIH/85-criar-endpoints-de-cadastro)
Criar um endpoint que é chamado ao usuário clicar no botão "REMOVER CONTA"
Criação do endpoint que recebe um PathVariable (userId)
|❌✅| Houve necessidade de modificações …

Criação do endpoint de desativação de conta

---

dockerfile

[Tarefa relacionada]()
Fazer o deploy da API contida no repositório ms-indespensa
Criação do dockerfile

Deploy do ms-indespensa no render

---

src/main/java/com/ottistech/indespensa/api/ms_indespensa/dto/SignUpUserDTO.java
src/main/java/com/ottistech/indespensa/api/ms_indespensa/dto/UserCredentialsResponse.java
src/main/java/com/ottistech/indespensa/api/ms_indespensa/dto/UserFullInfoResponse.java
src/main/java/com/ottistech/indespensa/api/ms_indespensa/exception/CepNotFoundException.java
src/main/java/com/ottistech/indespensa/api/ms_indespensa/model/Cep.java
src/main/java/com/ottistech/indespensa/api/ms_indespensa/model/User.java
src/main/java/com/ottistech/indespensa/api/ms_indespensa/service/UserService.java

[Tarefa relacionada](https://trello.com/c/UL0g5Ly4/95-atualiza%C3%A7%C3%B5es-com-adi%C3%A7%C3%A3o-da-idade)
Refatorar o projeto para criar um nova entidade chamada Cep e fazer mudanças em campos que retornamos dos nossos DTO's.
Criação de uma classe Entity Cep e CepRepository (interface). Refatoração de algumas classes que usavam campos da Entity Address para Entity Cep.
|✅| O código está legível e …

Refactoring all project

---

src/main/java/com/ottistech/indespensa/api/ms_indespensa/controller/UserController.java
src/main/java/com/ottistech/indespensa/api/ms_indespensa/dto/SignUpUserDTO.java
src/main/java/com/ottistech/indespensa/api/ms_indespensa/model/Address.java
src/main/java/com/ottistech/indespensa/api/ms_indespensa/repository/CepRepository.java
src/main/java/com/ottistech/indespensa/api/ms_indespensa/service/UserService.java

[Tarefa relacionada](https://trello.com/b/5BLwrWfB/indespensa)
Fazer o update do projeto para branch de QA. 
Subi tudo que havia na branch refactor/95/adding-age-data e fiz o PR.
|❌| Houve necessidade de modificações nas dependências …

Updating project

---

src/main/java/com/ottistech/indespensa/api/ms_indespensa/model/Brand.java
src/main/java/com/ottistech/indespensa/api/ms_indespensa/model/Product.java

[Tarefa relacionada](https://trello.com/c/543KOXNu/98-adi%C3%A7%C3%A3o-da-entidade-brand-no-ms-indespensa)
.
Representar a tabela **Brand** do banco de dados na API
.
Criação da entidade JPA brand, com seus relacionamentos e condições
|❌| Houve …

Criação da entidade Brand

---

src/main/java/com/ottistech/indespensa/api/ms_indespensa/MsIndespensaApplication.java
src/main/java/com/ottistech/indespensa/api/ms_indespensa/client/ProductRequestClient.java
src/main/java/com/ottistech/indespensa/api/ms_indespensa/config/FeignClientConfig.java
src/main/java/com/ottistech/indespensa/api/ms_indespensa/controller/ProductController.java
src/main/java/com/ottistech/indespensa/api/ms_indespensa/dto/ProductResponseApiDTO.java
src/main/java/com/ottistech/indespensa/api/ms_indespensa/dto/ProductResponseDTO.java
src/main/java/com/ottistech/indespensa/api/ms_indespensa/exception/EanCodeNotFoundException.java
src/main/java/com/ottistech/indespensa/api/ms_indespensa/exception/GlobalExceptionHandler.java
src/main/java/com/ottistech/indespensa/api/ms_indespensa/repository/BrandRepository.java
src/main/java/com/ottistech/indespensa/api/ms_indespensa/repository/CategoryRepository.java
src/main/java/com/ottistech/indespensa/api/ms_indespensa/repository/FoodRepository.java
src/main/java/com/ottistech/indespensa/api/ms_indespensa/repository/ProductRepository.java
src/main/java/com/ottistech/indespensa/api/ms_indespensa/service/ProductService.java
src/main/resources/application.properties

[Tarefa relacionada](https://trello.com/c/uylbOBrk/90-criar-endpoint-de-busca-de-produto-por-c%C3%B3digo-de-barras)
Facilitar a busca e o cadastro de produtos ao utilizar a função scanner do aplicativo mobile
Implementação de um endpoint que recebe um eancode e verifica se ele existe na nossa base de dados, caso não exista, faz um request em uma API externa, e caso não encontre, retorna HttpsStatus.NOT_FOUND
|✅| Minhas alterações não geram erros, bugs ou excessões inesperadas …

Search Product by Ean Code

---

src/main/java/com/ottistech/indespensa/api/ms_indespensa/controller/PantryItemController.java
src/main/java/com/ottistech/indespensa/api/ms_indespensa/dto/CreatePantryItemDTO.java
src/main/java/com/ottistech/indespensa/api/ms_indespensa/dto/PantryItemSimplifiedResponseDTO.java
src/main/java/com/ottistech/indespensa/api/ms_indespensa/dto/UserCredentialsResponse.java
src/main/java/com/ottistech/indespensa/api/ms_indespensa/model/PantryItem.java
src/main/java/com/ottistech/indespensa/api/ms_indespensa/repository/BrandRepository.java
src/main/java/com/ottistech/indespensa/api/ms_indespensa/repository/CategoryRepository.java
src/main/java/com/ottistech/indespensa/api/ms_indespensa/repository/FoodRepository.java
src/main/java/com/ottistech/indespensa/api/ms_indespensa/repository/PantryItemRepository.java
src/main/java/com/ottistech/indespensa/api/ms_indespensa/repository/ProductRepository.java
src/main/java/com/ottistech/indespensa/api/ms_indespensa/service/PantryItemService.java
src/main/java/com/ottistech/indespensa/api/ms_indespensa/service/ProductService.java
src/main/resources/application.properties

[Tarefa relacionada](https://trello.com/c/NShHyDoV/104-cria%C3%A7%C3%A3o-dos-endpoints-de-cadastro-de-item-da-despensa)
Criação de um endpoint que permite ao usuário inserir itens à sua despensa, garantindo que os produtos sejam corretamente associados e evitando duplicação.
Implementação do PantryItemService com as seguintes funcionalidades:
* Validação e Criação de Produtos: O serviço verifica se o produto já existe no banco de dados com base no código EAN. Se não existir, um novo produto é criado. Adicionada a lógica para verificar a existência do produto pelo nome, caso o código EAN não esteja disponível.
* Busca e Criação de Outras Entidades: Implementado métodos para buscar ou criar entidades relacionadas, como Brand, Food, e Category. As buscas são realizadas de forma a ignorar …

Endpoint de adicionar item à despensa

---

.github/workflows/ms-qa-cd-pipeline.yml
.github/workflows/ms-qa-ci-pipeline.yml
.github/workflows/ms-qa-pipeline.yml

[Tarefa relacionada](https://trello.com/c/yAvuMBXK/49-melhora-das-pipelines-de-ci-e-cd)
Criar pipeline para fazer deploy automático da API, junto com build da aplicação.
Criação de um novo workflow para branch de QA afim de testes.

Pipeline QA 

---

src/main/java/com/ottistech/indespensa/api/ms_indespensa/controller/UserController.java
src/main/java/com/ottistech/indespensa/api/ms_indespensa/dto/UpdateUserDTO.java
src/main/java/com/ottistech/indespensa/api/ms_indespensa/dto/UpdateUserResponseDTO.java
src/main/java/com/ottistech/indespensa/api/ms_indespensa/service/UserService.java

[Tarefa relacionada](https://trello.com/c/844UiUmF/88-criar-endpoints-de-atualiza%C3%A7%C3%A3o-de-usu%C3%A1rio)
Criar um endpoint ao qual usuários podem atualizar suas informações no aplicativo.
Criação de um endpoint do tipo PUT, que recebe as informações que o usuário colocou no input do aplicativo. No service, é feita as seguintes validações:
- Verificação se o usuário existe
- Verificação se o email já está em uso por outro usuário
- Verificação se o CEP passado pelo usuário já não está no banco, se estiver, atribui o usuário a ele, caso contrário, cria um novo CEP
|✅| Testei extensivamente meu recurso …

Endpoint that update user

---

pom.xml
src/main/java/com/ottistech/indespensa/api/ms_indespensa/client/ProductClientService.java
src/main/java/com/ottistech/indespensa/api/ms_indespensa/client/ProductRequestClient.java
src/main/java/com/ottistech/indespensa/api/ms_indespensa/exception/GlobalExceptionHandler.java
src/main/java/com/ottistech/indespensa/api/ms_indespensa/exception/JsonParcealizationException.java
src/main/java/com/ottistech/indespensa/api/ms_indespensa/service/ProductService.java

[Tarefa relacionada](https://trello.com/c/p77DqN4s/111-refatorar-a-api-para-tratar-os-erros-da-api-externa)
Por conta da API que estamos utilizando para encontrar código de barras dos produtos que os usuários escaneiam estar ocorrendo problemas com a response, é necessário implementar uma forma de manipular essa response para pegar apenas a parte do JSON. Dessa forma, será possível fazer o mapeamento do response para DTOs. 
Foi criado um service que é responsável de tratar do response da API externa utilizada no backend. Além disso, foi criado também tratamentos de exceções que podem ocorrer ao fazer a serialização de JSON em uma entitdade.
| --- | -------------------------------------------------------------- …

Fix external API

---

src/main/java/com/ottistech/indespensa/api/ms_indespensa/dto/UpdateUserDTO.java
src/main/java/com/ottistech/indespensa/api/ms_indespensa/dto/UpdateUserResponseDTO.java
src/main/java/com/ottistech/indespensa/api/ms_indespensa/service/UserService.java

Fazer atualizações de usuários do tipo ENTERPRISE
Adição do campo enterpriseType na dinâmica de atualização

Adicionando Tipo de Empresa ao Update User

---

src/main/java/com/ottistech/indespensa/api/ms_indespensa/controller/CategoryController.java
src/main/java/com/ottistech/indespensa/api/ms_indespensa/exception/CategoryNotFoundException.java
src/main/java/com/ottistech/indespensa/api/ms_indespensa/exception/GlobalExceptionHandler.java
src/main/java/com/ottistech/indespensa/api/ms_indespensa/repository/CategoryRepository.java
src/main/java/com/ottistech/indespensa/api/ms_indespensa/service/CategoryService.java

[Tarefa relacionada](https://trello.com/c/pZ4lgSP0/115-criar-endpoint-de-listagem-de-categorias)
Obter as categorias existentes com base em um padrão de letras
Criar um endpoint para consulta dos nomes das categorias com opção de filtro
|❌| Houve …

Listagem de categorias

---

src/main/java/com/ottistech/indespensa/api/ms_indespensa/controller/UserController.java
src/main/java/com/ottistech/indespensa/api/ms_indespensa/service/UserService.java

Permitir que o usuário seja notificado de mudanças nas credenciais
Adição das credenciais ao fluxo de atualização

Adicionando credenciais à atualização

---

src/main/java/com/ottistech/indespensa/api/ms_indespensa/controller/PantryItemController.java
src/main/java/com/ottistech/indespensa/api/ms_indespensa/dto/PartialPantryItemDTO.java
src/main/java/com/ottistech/indespensa/api/ms_indespensa/exception/GlobalExceptionHandler.java
src/main/java/com/ottistech/indespensa/api/ms_indespensa/exception/PantryItemNotFoundException.java
src/main/java/com/ottistech/indespensa/api/ms_indespensa/repository/PantryItemRepository.java
src/main/java/com/ottistech/indespensa/api/ms_indespensa/service/PantryItemService.java

[Tarefa relacionada](https://trello.com/c/MCxMn2Xw/123-cria%C3%A7%C3%A3o-do-endpoint-de-listagem-da-despensa)
Possibilitar que o usuário verifique o estado atual de sua despensa
Endpoint de consulta de itens ativos por usuário
|❌| Houve necessidade de …

Listagem de Itens da Despensa

---

src/main/java/com/ottistech/indespensa/api/ms_indespensa/controller/ShopItemController.java
src/main/java/com/ottistech/indespensa/api/ms_indespensa/dto/request/AddShopItemDTO.java
src/main/java/com/ottistech/indespensa/api/ms_indespensa/dto/response/ShopItemResponseDTO.java
src/main/java/com/ottistech/indespensa/api/ms_indespensa/model/ShopItem.java
src/main/java/com/ottistech/indespensa/api/ms_indespensa/repository/ShopItemRepository.java
src/main/java/com/ottistech/indespensa/api/ms_indespensa/service/ShopItemService.java
src/main/resources/application.properties

[Tarefa relacionada](https://trello.com/c/qQaWfcy7/126-cria%C3%A7%C3%A3o-do-endpoint-de-adi%C3%A7%C3%A3o-%C3%A0-lista-de-compras)
Criação de endpoint para adicionar um item à lista de compras do usuário
Criação do endpoint de criação `@PostMapping("/{user_id}/add")` com verificações no `@Service` de:
- Se o usuário já tem o productId registrado, apenas somar com o amount passado no request
- Caso, contrário, apenas cria-lo com o amount passado no request
|✅| Minhas alterações …

Endpoint add item to shopping-list

---

src/main/java/com/ottistech/indespensa/api/ms_indespensa/controller/PantryItemController.java
src/main/java/com/ottistech/indespensa/api/ms_indespensa/dto/UpdatePantryItemDTO.java
src/main/java/com/ottistech/indespensa/api/ms_indespensa/service/PantryItemService.java

[Tarefa relacionada]()
Permitir que o usuário altere a quantidade de cada item em sua despensa
Criação de um endpoint que atualiza a quantidade de múltiplos itens de uma vez …

Atualização de Item da Despensa

---

src/main/java/com/ottistech/indespensa/api/ms_indespensa/repository/PantryItemRepository.java
src/main/java/com/ottistech/indespensa/api/ms_indespensa/service/PantryItemService.java

Ao inserir um item na despensa com o mesmo produto, usuário e data de validade, era gerado um novo item, o que não devia acontecer. Esse código corrige isso.
Verificar a existência de um item despensa com as mesmas características e, se existir, apenas incrementar a quantidade
|✅| Minhas alterações atendem aos requisitos de …

Prevenção de itens duplicados na despensa

---

src/main/java/com/ottistech/indespensa/api/ms_indespensa/controller/PantryItemController.java
src/main/java/com/ottistech/indespensa/api/ms_indespensa/dto/PantryItemCreateDTO.java
src/main/java/com/ottistech/indespensa/api/ms_indespensa/dto/PantryItemPartialDTO.java
src/main/java/com/ottistech/indespensa/api/ms_indespensa/dto/response/PantryItemDetailsDTO.java
src/main/java/com/ottistech/indespensa/api/ms_indespensa/repository/PantryItemRepository.java
src/main/java/com/ottistech/indespensa/api/ms_indespensa/service/PantryItemService.java

[Tarefa relacionada](https://trello.com/c/AcE8RUoq/125-cria%C3%A7%C3%A3o-do-endpoint-de-leitura-de-um-item-da-despensa)
Mostrar ao usuário detalhes de um item específico da despensa.
Criação de um endpoint que recebe um id da despensa e retorna seus detalhes, caso exista
|✅| Minhas alterações atendem aos requisitos de negócio …

Detalhes do item da despensa

---

src/main/java/com/ottistech/indespensa/api/ms_indespensa/dto/response/PantryItemDetailsDTO.java

[Tarefa relacionada]()
Enviar o productId de volta ao inserir na lista de compras pelo mobile
Adição do productId ao DTO de detalhes de item da despensa

Adição do productId aos details

---

src/main/java/com/ottistech/indespensa/api/ms_indespensa/controller/PantryItemController.java
src/main/java/com/ottistech/indespensa/api/ms_indespensa/dto/request/AddPantryItemDTO.java
src/main/java/com/ottistech/indespensa/api/ms_indespensa/dto/response/PantryItemResponseDTO.java
src/main/java/com/ottistech/indespensa/api/ms_indespensa/dto/response/ShopItemResponseDTO.java
src/main/java/com/ottistech/indespensa/api/ms_indespensa/model/PantryItem.java
src/main/java/com/ottistech/indespensa/api/ms_indespensa/model/ShopItem.java
src/main/java/com/ottistech/indespensa/api/ms_indespensa/repository/PantryItemRepository.java
src/main/java/com/ottistech/indespensa/api/ms_indespensa/repository/ShopItemRepository.java
src/main/java/com/ottistech/indespensa/api/ms_indespensa/service/PantryItemService.java
src/main/java/com/ottistech/indespensa/api/ms_indespensa/service/ShopItemService.java

[Tarefa relacionada](https://trello.com/c/H4NJ67BE/140-cria%C3%A7%C3%A3o-do-endpoint-de-adicionar-todos-os-itens-da-lista-de-compras-%C3%A0-despensa)
Possibilitar que itens sejam transferidos da lista de compras à despensa de forma simples
Criação de dois endpoints:
- Adição de toda a lista de compras do usuário à despensa
- Adição de um item da lista de compras à despensa do usuário
|✅| O código está …

Adição à despensa via lista de compras

---

src/main/java/com/ottistech/indespensa/api/ms_indespensa/controller/ProductController.java
src/main/java/com/ottistech/indespensa/api/ms_indespensa/repository/ProductRepository.java
src/main/java/com/ottistech/indespensa/api/ms_indespensa/service/ProductService.java

[Tarefa relacionada](https://trello.com/c/jrMcXuH6/143-criar-endpoint-de-busca-de-produtos)
Buscar informações de produto por nome começando por algum conjunto de letras
Criação do endpoint de busca de produtos
|❌| Houve necessidade de modificações nas …

Busca de produtos

---

src/main/java/com/ottistech/indespensa/api/ms_indespensa/controller/UserController.java
src/main/java/com/ottistech/indespensa/api/ms_indespensa/exception/GlobalExceptionHandler.java
src/main/java/com/ottistech/indespensa/api/ms_indespensa/exception/UserAlreadyIsPremiumException.java
src/main/java/com/ottistech/indespensa/api/ms_indespensa/service/UserService.java

[Tarefa relacionada](https://trello.com/c/kE29qreb/150-cria%C3%A7%C3%A3o-do-endpoint-de-tornar-o-usu%C3%A1rio-para-premium)
Fazer com que usuários possam se tornar Premium.
- Verificação de Existência do Usuário
- O endpoint aceita um userId como parâmetro na URL.
Verifica se o userId existe no banco de dados:
Se não existir, retorna um código de status 404 Not Found.
- Verificação do Status Premium
- Se o userId existir, o sistema verifica se o usuário já possui o status premium
Se o usuário já for premium, retorna um código de status 410 Gone.
- Atualização do Status Premium
- Se o usuário não for premium, atualiza o campo correspondente de false para true, concedendo ao usuário o status premium.
| --- | …

Endpoint to user become premium

---

src/main/java/com/ottistech/indespensa/api/ms_indespensa/config/WebConfig.java

Consumir a API no navegador
Adicionar política de CORS em classe de configuração
- Todas as origens foram permitidas

Adicionando política de CORS

---

src/main/java/com/ottistech/indespensa/api/ms_indespensa/controller/RecipeController.java
src/main/java/com/ottistech/indespensa/api/ms_indespensa/dto/request/CreateRecipeDTO.java
src/main/java/com/ottistech/indespensa/api/ms_indespensa/dto/request/CreateRecipeIngredientDTO.java
src/main/java/com/ottistech/indespensa/api/ms_indespensa/dto/response/RecipeFullInfoResponseDTO.java
src/main/java/com/ottistech/indespensa/api/ms_indespensa/dto/response/RecipeIngredientDetailsDTO.java
src/main/java/com/ottistech/indespensa/api/ms_indespensa/model/Recipe.java
src/main/java/com/ottistech/indespensa/api/ms_indespensa/model/RecipeIngredient.java
src/main/java/com/ottistech/indespensa/api/ms_indespensa/repository/RecipeIngredientRepository.java
src/main/java/com/ottistech/indespensa/api/ms_indespensa/repository/RecipeRepository.java
src/main/java/com/ottistech/indespensa/api/ms_indespensa/service/RecipeService.java

[Tarefa relacionada](https://trello.com/c/E53cgQLh/155-endpoint-de-cria%C3%A7%C3%A3o-de-receita)
Permitir que os usuários possam criar novas receitas no aplicativo.
Criação do endpoint, junto com validações, verificações e etc.
Exemplo de **request**:
```javascript
{
"createdBy": 21,
"title": "Bolo de Cenoura",
"description": "Um bolo de cenoura delicioso",
"level": "Médio",
"preparationTime": 80,
"preparationMethod": "Misture tudo, asse e coma",
"isShared": true,
"createRecipeIngredientList": [
{
"foodId": 17,
"amount": 3,
"unit": "u",
"isEssential": true
}
]
}
``` 
Exemplo de **response**:
HTTP_STATUS: `CREATED (201)`
```javascript
{
"recipeId": 13,
"createdBy": 21,
"title": "Bolo de Cenoura",
"description": "Um bolo de cenoura delicioso",
"level": "Médio",
"preparationTime": 80, …
```

Endpoint create recipe

---

src/main/java/com/ottistech/indespensa/api/ms_indespensa/MsIndespensaApplication.java
src/main/java/com/ottistech/indespensa/api/ms_indespensa/controller/RecipeController.java
src/main/java/com/ottistech/indespensa/api/ms_indespensa/dto/request/CreateRecipeDTO.java
src/main/java/com/ottistech/indespensa/api/ms_indespensa/dto/response/RecipeFullInfoResponseDTO.java
src/main/java/com/ottistech/indespensa/api/ms_indespensa/dto/response/RecipePartialResponseDTO.java
src/main/java/com/ottistech/indespensa/api/ms_indespensa/exception/GlobalExceptionHandler.java
src/main/java/com/ottistech/indespensa/api/ms_indespensa/model/Recipe.java
src/main/java/com/ottistech/indespensa/api/ms_indespensa/repository/PantryItemRepository.java
src/main/java/com/ottistech/indespensa/api/ms_indespensa/repository/RecipeRepository.java
src/main/java/com/ottistech/indespensa/api/ms_indespensa/service/RecipeService.java

[Tarefa relacionada](https://trello.com/c/ClEDumSB/159-endpoint-de-listagem-de-receitas)
Permitir que o cliente possa ter acesso a diversas receitas no aplicativo.
Foi implementado um endpoint que busca receitas de forma paginada, recebendo na URL os seguintes campos:
`recipes/list?page=0&size=10&userId=21`
Esse endpoint retorna o seguinte JSON:
```javascript
{
"content": [
{
"recipeId": 13,
"imageUrl": null,
"title": "Bolo de Cenoura",
"description": "Um bolo de cenoura delicioso",
"amountIngredients": 2,
"amountInPantry": 2,
"level": "Médio",
"preparationTime": 80,
"numStars": 0
},
{
"recipeId": 14,
"imageUrl": null,
"title": "Arroz Branco",
"description": "Delicioso arroz branco sem segredo, simples, prático e rápido.",
"amountIngredients": 5,
"amountInPantry": 1,
"level": "Fácil", …
```

Endpoint List Recipes

---

src/main/java/com/ottistech/indespensa/api/ms_indespensa/MsIndespensaApplication.java
src/main/java/com/ottistech/indespensa/api/ms_indespensa/controller/RecipeController.java
src/main/java/com/ottistech/indespensa/api/ms_indespensa/dto/request/CreateRecipeDTO.java
src/main/java/com/ottistech/indespensa/api/ms_indespensa/dto/request/CreateRecipeIngredientDTO.java
src/main/java/com/ottistech/indespensa/api/ms_indespensa/dto/response/RecipeDetailsDTO.java
src/main/java/com/ottistech/indespensa/api/ms_indespensa/dto/response/RecipeFullInfoResponseDTO.java
src/main/java/com/ottistech/indespensa/api/ms_indespensa/dto/response/RecipeIngredientDetailsDTO.java
src/main/java/com/ottistech/indespensa/api/ms_indespensa/dto/response/RecipePartialResponseDTO.java
src/main/java/com/ottistech/indespensa/api/ms_indespensa/exception/GlobalExceptionHandler.java
src/main/java/com/ottistech/indespensa/api/ms_indespensa/model/Recipe.java
src/main/java/com/ottistech/indespensa/api/ms_indespensa/model/RecipeIngredient.java
src/main/java/com/ottistech/indespensa/api/ms_indespensa/repository/PantryItemRepository.java
src/main/java/com/ottistech/indespensa/api/ms_indespensa/repository/RecipeIngredientRepository.java
src/main/java/com/ottistech/indespensa/api/ms_indespensa/repository/RecipeRepository.java
src/main/java/com/ottistech/indespensa/api/ms_indespensa/service/RecipeService.java

[Tarefa relacionada](https://trello.com/c/7JLtnlEW/156-endpoint-de-leitura-de-receita)
Permitir que o usuário visualize individualmente os detalhes de uma receita.
Criação de um endpoint que recebe o ID da receita como `@PathVariable` e o ID do usuário como `@RequestParam`. É verificado se ambos existem na camada de Service antes de retornar uma resposta completa.
Exemplo de request: `/recipes/13/details?userId=21` 
Exemplo de resposta:
```javascript
{
"recipeId": 13,
"imageUrl": null,
"level": "Médio",
"title": "Bolo de Cenoura",
"numStars": 0,
"description": "Um bolo de cenoura delicioso",
"amountIngredients": 2,
"amountInPantry": 2,
"preparationTime": 80,
"preparationMethod": "Misture tudo, asse e coma",
"ingredients": [
{
"foodName": "Água",
"amount": 1.00,
"unit": "L",
"isEssential": …
```

Endpoint Recipe Details

---

src/main/java/com/ottistech/indespensa/api/ms_indespensa/controller/RecipeController.java
src/main/java/com/ottistech/indespensa/api/ms_indespensa/dto/request/RateRecipeRequestDTO.java
src/main/java/com/ottistech/indespensa/api/ms_indespensa/model/CompletedRecipe.java
src/main/java/com/ottistech/indespensa/api/ms_indespensa/repository/CompletedRecipeRepository.java
src/main/java/com/ottistech/indespensa/api/ms_indespensa/service/RecipeService.java

[Tarefa relacionada](https://trello.com/c/je8KLo6V/157-endpoint-de-fazer-avaliar-receita)
Permitir que o usuário possa fazer/avaliar uma receita.
Endpoint que verifica se o usuário existe, se a receita existe, e se ela já não foi avaliada. Se já foi, é atualizado, senão, é criado.
Exemplo de request:
`recipes/13/rating`
```javascript
{
"userId": 21,
"numStars": 2
}
``` 
Response: `HttpStatus.NO_CONTENT` …

Endpoint Recipe Rating

---

src/main/java/com/ottistech/indespensa/api/ms_indespensa/controller/RecipeController.java
src/main/java/com/ottistech/indespensa/api/ms_indespensa/dto/response/ProductSearchResponseDTO.java
src/main/java/com/ottistech/indespensa/api/ms_indespensa/dto/response/RecipeFullInfoResponseDTO.java
src/main/java/com/ottistech/indespensa/api/ms_indespensa/dto/response/RecipeIngredientDetailsDTO.java
src/main/java/com/ottistech/indespensa/api/ms_indespensa/exception/GlobalExceptionHandler.java
src/main/java/com/ottistech/indespensa/api/ms_indespensa/model/Recipe.java
src/main/java/com/ottistech/indespensa/api/ms_indespensa/repository/ProductRepository.java
src/main/java/com/ottistech/indespensa/api/ms_indespensa/repository/RecipeIngredientRepository.java
src/main/java/com/ottistech/indespensa/api/ms_indespensa/repository/RecipeRepository.java
src/main/java/com/ottistech/indespensa/api/ms_indespensa/service/RecipeService.java
src/main/java/com/ottistech/indespensa/api/ms_indespensa/utils/enums/Availability.java
src/main/java/com/ottistech/indespensa/api/ms_indespensa/utils/enums/Difficulty.java

[Tarefa relacionada](https://trello.com/c/TzDNxDpl/165-endpoint-de-filtro-de-receitas)
Permitir que o usuários premium possam filtras receitas.
No endpoint de listar receitas, foi criado mais mais 4 `@RequestParam`, sendo eles:
```java
@RequestParam(required = false, defaultValue = "") Difficulty difficulty,
@RequestParam(required = false, defaultValue = "OUT_OF_PANTRY") Availability availability,
@RequestParam(required = false) Integer startPreparationTime,
@RequestParam(required = false) Integer endPreparationTime
``` 
Um exemplo de request seria: `http://localhost:8080/api/v1/recipes/list?userId=21&difficulty=MEDIUM`
Response: 
```javascript
{
"content": [
{
"recipeId": 13,
"imageUrl": null,
"title": "Bolo de Cenoura",
"description": "Um bolo de cenoura delicioso",
"amountIngredients": …
```

Endpoint Recipe Filters

---

.gitignore
pom.xml
src/main/java/com/ottistech/indespensa/api/ms_indespensa/config/SecurityConfig.java
src/main/java/com/ottistech/indespensa/api/ms_indespensa/controller/UserController.java
src/main/java/com/ottistech/indespensa/api/ms_indespensa/dto/response/UserCredentialsTokenResponseDTO.java
src/main/java/com/ottistech/indespensa/api/ms_indespensa/service/JwtTokenService.java
src/main/java/com/ottistech/indespensa/api/ms_indespensa/service/UserService.java
src/main/resources/application.properties

[Tarefa relacionada](https://trello.com/c/IZV8aaQr/86-configura%C3%A7%C3%A3o-do-spring-security)
Configurar o projeto para utilizar autenticação e autorização nos endpoints de admin.
Foi criado uma classe de configuração chamada `SecurityConfig.java` e nela tem toda configuração de `FilterChain`, `JwtEncoder`, `BCryptPasswordEncoder `e `JwtAuthenticationConverter`.
|✅| O código está legível e …

Implementing Spring Security

---

src/main/java/com/ottistech/indespensa/api/ms_indespensa/controller/PantryItemController.java
src/main/java/com/ottistech/indespensa/api/ms_indespensa/dto/response/PantryItemsNextToValidityDate.java
src/main/java/com/ottistech/indespensa/api/ms_indespensa/repository/PantryItemRepository.java
src/main/java/com/ottistech/indespensa/api/ms_indespensa/service/PantryItemService.java

[Tarefa relacionada](https://trello.com/c/0ahiLMRz/160-endpoint-de-pr%C3%B3ximos-vencimentos)
Foi criado um novo endpoint com o objetivo de permitir que os usuários visualizem quais produtos estão próximos do vencimento em sua despensa.
Criação de um novo endpoint, junto com seus DTO's e respectivas queries.
Exemplo de request:
`/api/v1/pantry/3/soon-to-expire`
Exemplo de response:
```javascript
[
{
"productName": "Açúcar União ",
"amount": 1,
"unit": "kg",
"validityDate": "2024-10-16"
},
{
"productName": "Milk Shake Cremoso",
"amount": 1,
"unit": "ml",
"validityDate": "2024-10-17"
}
]
``` 
|✅| Testei extensivamente meu recurso …

Endpoint Items Next to Validity Date

---

src/main/java/com/ottistech/indespensa/api/ms_indespensa/controller/DashboardController.java
src/main/java/com/ottistech/indespensa/api/ms_indespensa/controller/RecipeController.java
src/main/java/com/ottistech/indespensa/api/ms_indespensa/dto/response/DashboardInfoDTO.java
src/main/java/com/ottistech/indespensa/api/ms_indespensa/dto/response/DashboardPersonalInfoDTO.java
src/main/java/com/ottistech/indespensa/api/ms_indespensa/dto/response/DashboardProfileInfoDTO.java
src/main/java/com/ottistech/indespensa/api/ms_indespensa/repository/CompletedRecipeRepository.java
src/main/java/com/ottistech/indespensa/api/ms_indespensa/repository/PantryItemRepository.java
src/main/java/com/ottistech/indespensa/api/ms_indespensa/repository/RecipeRepository.java
src/main/java/com/ottistech/indespensa/api/ms_indespensa/repository/ShopItemRepository.java
src/main/java/com/ottistech/indespensa/api/ms_indespensa/service/DashboardService.java
src/main/java/com/ottistech/indespensa/api/ms_indespensa/service/RecipeService.java

[Tarefa relacionada](https://trello.com/c/4CbdjvBk/174-endpoints-do-perfil-pessoal)
Permitir que o usuário visualize todas as informações da tela Perfil Pessoal.
Criação de um novo endpoint, para receber as informações que ficarão no dashboard da tela Perfil Pessoa, e adição de um novo campo do endpoint /recipes/list?createdByYou, que busca uma query ao qual faz o filtro de receitas criadas pelo usuário passado.
|✅| Minhas alterações não geram erros, bugs ou excessões …

Endpoints Profile

---

src/main/java/com/ottistech/indespensa/api/ms_indespensa/repository/PantryItemRepository.java
src/main/java/com/ottistech/indespensa/api/ms_indespensa/repository/ShopItemRepository.java
src/main/java/com/ottistech/indespensa/api/ms_indespensa/service/ShopItemService.java

[Tarefa relacionada](https://trello.com/c/0ZKiQM2U/189-fix-ordenar-datas-da-mais-pr%C3%B3xima-para-a-mais-distante)
Permitir melhor entendimento das informações recebidas estrategicamente
Queries sendo ordenadas corretamente.
|❌| Houve necessidade de …

Ordering dates

---

src/main/java/com/ottistech/indespensa/api/ms_indespensa/controller/UserController.java
src/main/java/com/ottistech/indespensa/api/ms_indespensa/controller/contract/UserContract.java
src/main/java/com/ottistech/indespensa/api/ms_indespensa/exception/GlobalExceptionHandler.java
src/main/java/com/ottistech/indespensa/api/ms_indespensa/exception/UserAlreadyIsPremiumException.java
src/main/java/com/ottistech/indespensa/api/ms_indespensa/service/UserService.java

[Tarefa relacionada](https://trello.com/c/iB3Ob3PN/191-cria%C3%A7%C3%A3o-da-funcionalidade-de-cancelamento-do-plano-premium)
Permitir que os usuários interrompam o pagamento e seus benefícios premium
Ao invés de criar um outro endpoint, foi refatorado o endpoint de atualização para plano premium para que se o usuário for premium, e fazer request nesse endpoint, ele cancela seu plano, caso contrário, vira premium.
|✅| Minhas alterações não geram erros, bugs ou excessões …

Implementing User Cancel Premium
